In [ ]:
#In this notebook I want to show that matrix multiplication is way faster on numpy than using for loops

import numpy as np #import numpy and call it np
import time

In [ ]:
"""
Example of Matrix Multiplication

A = 1 2  B = 1 2  C = A*B = 1*1+2*3 1*2+2*4 =  7 10 
    3 4      3 4            3*1+4*3 3*2+4*4   15 22
"""

def matrix_mul_for(Matrix_A, Matrix_B, m_dim, l_dim, k_dim): #Matrix multiplication with for loop
  C = [] #C = A*B

  for n in range(m_dim): #C has m rows therefore m_dim
    c_row = []
    for m in range(k_dim): #C has k rows therefore k_dim
      c_row.append(sum([Matrix_A[n][i] * Matrix_B[i][m] for i in range(l_dim)])) #Multiplication of row in A with column in B
    C.append(c_row)

  
  return C

#Generate Matrix for the Test

m_dim = 5
l_dim = 1000
k_dim = 5

A = [[x + i for x in range(l_dim)] for i in range(m_dim)] #Proportions of A: m x l
B = [[x     for x in range(k_dim)] for i in range(l_dim)] #Proportions of B: l x k
C = []                                                    #Proportions of C: m x k

#For Loop Matrix Multiplication 

start = time.time()
for i in range (1000):
  C = matrix_mul_for(A, B, m_dim, l_dim, k_dim)
stop  = time.time()

print(f"Matrix multiplication for loop \ntime: {stop - start}s \nMatrix: {C}\n")


#Numpy Matrix Multiplication

A_np = np.matrix(A)
B_np = np.matrix(B)

start = time.time()
for i in range(1000):
 C_np = np.matmul(A_np, B_np) #In short form: A_np @ B_np
stop  = time.time()

print(f"Matrix multiplication for numpy \ntime: {stop - start}s \nMatrix: {C_np}")

#As you can see the Matrix multiplication with for loop takes a lot more time than the multiplication with numpy
#Therefore it is a good idea to use numpy especially for large matrixes

Matrix multiplication for loop 
time: 4.194987773895264s 
Matrix: [[0, 499500, 999000, 1498500, 1998000], [0, 500500, 1001000, 1501500, 2002000], [0, 501500, 1003000, 1504500, 2006000], [0, 502500, 1005000, 1507500, 2010000], [0, 503500, 1007000, 1510500, 2014000]]

Matrix multiplication for numpy 
time: 0.0346834659576416s 
Matrix: [[      0  499500  999000 1498500 1998000]
 [      0  500500 1001000 1501500 2002000]
 [      0  501500 1003000 1504500 2006000]
 [      0  502500 1005000 1507500 2010000]
 [      0  503500 1007000 1510500 2014000]]
